### ISSUE TITLE
No name resolution on new Ubuntu 18.10 vm

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/WALinuxAgent#1476]
I can't reopen https://github.com/Azure/WALinuxAgent/issues/1151, but this is just that bug again, but on 18.10 instead of 18.04. The fix for this issue hard codes a 18.04 version check into the files, so it's broken for every Ubuntu image going forward.

**Comment by MattGal** [comment]
@narrieta could I get some kind of rough estimate when this might get addressed?

**Comment by jasonzio** [comment]
Looks like systemd is here to stay, so the fix is pretty obvious. Not sure why @ChadNedzlek couldn't have done the one-line PR themselves, but... whatever. Here it is.

**Comment by narrieta** [comment]
fixed by #1483

**Comment by MattGal** [comment]
This problem is still reproducing in the following Azure gallery images:
SKU: 18.10, Version: 18.10.201903200                  
SKU: 18.10-DAILY, Version:  18.10.201904190

I don't seem to be able to reactivate this issue though, should I open a new one?
