### ISSUE TITLE
[2.2.4+]Sometimes waagent fails to mount the local disk partition

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#600]
Description of problem:
Sometimes the waagent mount the local disk partition (/dev/sdb1) before it exists, so that the mount is failed.
The error code of "mount: special device /dev/sdd1 does not exist" is 32, which is the same as "mount: /dev/sdb1 is already mounted" error code. As a result, the waagent regards the "device does not exist" as "already mounted" and create swap file directly even if the /dev/sdb1 is not mounted.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.2.4/2.2.5

RHEL Version:
RHEL-7.3 on-demand image

How reproducible:
30%

Steps to Reproduce:
1. Prepare a RHEL-7.3 VM(Standard_A1) with WALA-2.2.4-1 installed and enabled. Set "ResourceDisk.EnableSwap=y"
2. Reboot the VM.
3. After the VM is booted, check the swap and the mount status:
free -m
mount

Actual Result:
The swap size is 0. The local disk partition is not mounted.

Expect Result:
The local disk partition is mounted.

/var/log/waagent.log:
```
2017/03/02 11:40:45.629813 INFO Activate resource disk
2017/03/02 11:40:45.666904 INFO Examining partition table
2017/03/02 11:40:45.722347 INFO GPT not detected, determining filesystem
2017/03/02 11:40:45.749369 INFO sfdisk with --part-type failed [1], retrying with -c
2017/03/02 11:40:45.778195 INFO sfdisk -c -f /dev/sdb 1 succeeded
2017/03/02 11:40:45.778361 INFO The partition type is 83
2017/03/02 11:40:45.778469 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/03/02 11:40:45.808002 WARNING Resource disk is already mounted: mount: special device /dev/sdb1 does not exist

2017/03/02 11:40:45.808140 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/03/02 11:40:45.810434 INFO Enable swap
2017/03/02 11:40:45.869825 INFO Create swap file
2017/03/02 11:40:46.141439 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2017/03/02 11:40:46.142272 ERROR Error Code:255
2017/03/02 11:40:46.142349 ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument

2017/03/02 11:40:46.142457 ERROR Failed to enable swap (000005)/mnt/resource/swapfile
```

Additional Info:
1. I've rebooted 100 times on RHEL-7.3 and this issue occurs 30 times. I also tried 100 times on RHEL-6.9 and it is not observed.
2. It seems that only small size VM(like A1, A2, D1_v2) have this issue. In the large size(D5_v2) it isn't observed.

**Comment by hglkrijger** [comment]
@yuxisun1217, which region are you deploying to? Could you let me know the exact image you are using?

**Comment by yuxisun1217** [comment]
Hi @hglkrijger , the region is Southeast Asia. kernel: 3.10.0-514.6.2.el7.x86_64

**Comment by hglkrijger** [comment]
@yuxisun1217, so far I have not been able to reproduce this issue. I merged a potential fix with #613 which should address this if it happens, but as yet I have not been able to verify it. Would you mind updating your VM with these latest changes and seeing whether you still hit the issue?

**Comment by hglkrijger** [comment]
@yuxisun1217, will close this for now. Let me know if the fix does not work.

**Comment by yuxisun1217** [comment]
Hi @hglkrijger ,

Sorry I just notice this comment. I install WALA-2.2.6 in RHEL-7 and this issue still exists.

2017/03/20 05:25:33.297211 WARNING Could not mount resource disk: mount: special device /dev/sdb1 does not exist

```
2017/03/20 02:58:19.533735 INFO GPT not detected, determining filesystem
2017/03/20 02:58:19.568417 INFO sfdisk with --part-type failed [1], retrying with -c
2017/03/20 02:58:19.596427 INFO sfdisk -c -f /dev/sdb 1 succeeded
2017/03/20 02:58:19.611842 INFO The partition type is 83
2017/03/20 02:58:19.612032 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/03/20 02:58:19.664973 WARNING Resource disk is already mounted: mount: special device /dev/sdb1 does not exist

2017/03/20 02:58:19.665175 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/03/20 02:58:19.665561 INFO Enable swap
2017/03/20 02:58:19.743158 INFO Create swap file
2017/03/20 02:58:19.916704 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2017/03/20 02:58:19.916935 ERROR Error Code:255
2017/03/20 02:58:19.917052 ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument

2017/03/20 02:58:19.917224 ERROR Failed to enable swap (000005)/mnt/resource/swapfile
```

I print some logs here (/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py):
```
156         attempts = 5
157         logger.warn("===========")
158         aaa=os.path.exists(partition)
159         bbb=attempts > 0
160         logger.warn(str(aaa)+"|"+str(bbb))
161 #        while not os.path.exists(partition) and attempts > 0:
162         while not aaa and bbb:
163             logger.info("Waiting for partition [{0}], {1} attempts remaining",
164                         partition,
165                         attempts)
166             sleep(5)
167             attempts -= 1
168             aaa=os.path.exists(partition)
169             bbb=attempts > 0
170             logger.warn(str(aaa)+"|"+str(bbb))
171 
172         if not os.path.exists(partition):
173             raise ResourceDiskError("Partition was not created [{0}]".format(partition))
```

And then print this log(It's really hard to reproduce it after I changed the code. Reboot about 20 times.)
```
2017/03/20 08:22:29.668244 INFO GPT not detected, determining filesystem
2017/03/20 08:22:29.668549 VERBOSE run cmd 'sfdisk --part-type -f /dev/sdb 1'
2017/03/20 08:22:29.689342 INFO sfdisk with --part-type failed [1], retrying with -c
2017/03/20 08:22:29.689493 VERBOSE run cmd 'sfdisk -c -f /dev/sdb 1'
2017/03/20 08:22:29.734557 INFO sfdisk -c -f /dev/sdb 1 succeeded
2017/03/20 08:22:29.743858 INFO The partition type is 83
2017/03/20 08:22:29.744016 WARNING ===========
2017/03/20 08:22:29.744137 WARNING True|True
2017/03/20 08:22:29.744226 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/03/20 08:22:29.744315 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/20 08:22:29.783521 WARNING Could not mount resource disk: mount: special device /dev/sdb1 does not exist

2017/03/20 08:22:29.783721 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/03/20 08:22:29.811872 INFO Enable swap
2017/03/20 08:22:29.834598 VERBOSE run cmd 'swapon -s'
2017/03/20 08:22:29.867200 VERBOSE run cmd 'swapon /mnt/resource/swapfile'
2017/03/20 08:22:29.936622 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2017/03/20 08:22:29.936831 ERROR Error Code:255
2017/03/20 08:22:29.936919 ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument

2017/03/20 08:22:29.937074 ERROR Failed to enable swap (000005)/mnt/resource/swapfile
```

It seems that the "os.path.exists(partition)" result is "True", but when run "mount /dev/sdb1 /mnt/resource" it still shows "special device /dev/sdb1 does not exist". It's wired. I guess that the "/dev/sdb1" file exists doesn't really mean that this partition is ready. So I think maybe we have to catch the failure of "mount /dev/sdb1 /mnt/resource" and retry if it's failed.

**Comment by yuxisun1217** [comment]
Here's a script that we use to reproduce this issue:

cat set_reboot.sh
```
#!/bin/bash

if [ -f "/var/log/num" ];then
    global_num=`cat /var/log/num`
else
    global_num=0
fi

function handler()
{
    sleep 80
    num=`expr ${global_num} + 1`
    echo -e "${num}:\t"`date -R` >> /var/log/reboot.info
    echo -e "${num}:\t"`date -R` >> /var/log/waagent.log
    echo ${num} > /var/log/num
}
function is_not_run()
{
    if [ -f "/root/stop" ];then
        exit 253
    fi
    if [ ${global_num} == "100" ];then
        exit 252
    fi
}

function main()
{
    is_not_run
    handler
    reboot
}

main
```

Usage:
1. Put this script into RHEL-7 /root/ folder. chmod +x /root/set_reboot.sh
2. Add the following line into /etc/rc.d/rc.local:
bash /root/set_reboot.sh
3. chmod +x /etc/rc.d/rc.local
4. reboot the VM manually.
This script will keep rebooting the VM 100 times. The current reboot times is written in /var/log/num.

**Comment by hglkrijger** [comment]
Thanks @yuxisun1217, I will take another look at this.

**Comment by vittyvk** [comment]
Looking at mount(8) code I can see it returns '32' for all mount errors including ENOENT which reports 'special device %s does not exist' so the check:
	ret, output = shellutil.run_get_output(mount_string, chk_err=False)
        # if the exit code is 32, then the resource disk is already mounted                                                                                                                                        
        if ret == 32:
            logger.warn("Could not mount resource disk: {0}", output)
probably needs updating.

I didn't test it myself, but would 'os.sync()' inserted before 'ret, output = shellutil.run_get_output(mount_string, chk_err=False)' eliminate the race? @yuxisun1217 could you try?

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,

The os.sync() is new in python 3.3, but RHEL-7 is still using python 2.7.5. Is there a similar function in python2.7.5? Thanks.

**Comment by vittyvk** [comment]
Ah, yes, you can just do
ret, output = shellutil.run_get_output("sync")
instead

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,

I added the "sync" line in azurelinuxagent/daemon/resourcedisk/default.py and tried for 100 times:
167         logger.info("Mount resource disk [{0}]", mount_string)
168         ret, output = shellutil.run_get_output("sync")
169         ret, output = shellutil.run_get_output(mount_string, chk_err=False)

It seems can reduce the reproducible frequency, but still cannot prevent it hundred-percent. (reproduce 4/100 times)

Here're the logs:
2017/03/24 03:40:10.761650 INFO The partition type is 83
2017/03/24 03:40:10.761773 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/03/24 03:40:10.761855 VERBOSE run cmd 'sync'
2017/03/24 03:40:10.828250 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/24 03:40:10.858644 WARNING Could not mount resource disk: mount: special device /dev/sdb1 does not exist

2017/03/24 03:40:10.858846 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/03/24 03:40:10.874123 INFO Enable swap
2017/03/24 03:40:10.875103 VERBOSE run cmd 'swapon -s'
2017/03/24 03:40:10.898522 VERBOSE run cmd 'swapon /mnt/resource/swapfile'
2017/03/24 03:40:11.013104 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2017/03/24 03:40:11.013508 ERROR Error Code:255
2017/03/24 03:40:11.013678 ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument

2017/03/24 03:40:11.013816 ERROR Failed to enable swap (000005)/mnt/resource/swapfile

**Comment by vittyvk** [comment]
Ok, so this is definitely a race. I will take a look from kernel side (how can it happen that we have a device but it is not accessible for some time), could you please try one more hack to see if it helps or not:

replace "if ret == 32:" after "ret, output = shellutil.run_get_output(mount_string, chk_err=False)" with the following condition:
"if ret == 32 and s.find("is already mounted") != -1:"
so we'll get into 'elif' branch which has sfdisk/blockdev call?

**Comment by vittyvk** [comment]
sorry, it should be
"if ret == 32 and output.find("is already mounted") != -1:"

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,

I use both "sync" and "if ret == 32 and output.find("is already mounted") != -1:" this time:
```
167         logger.info("Mount resource disk [{0}]", mount_string)
168         ret, output = shellutil.run_get_output("sync")
169         ret, output = shellutil.run_get_output(mount_string, chk_err=False)
170         # if the exit code is 32, then the resource disk is already mounted
171 #        if ret == 32:
172         if ret == 32 and output.find("is already mounted") != -1:
173             logger.warn("Could not mount resource disk: {0}", output)
174         elif ret != 0:
```
I reboot 300 times and the error is not observed. 

I found some warning logs:
```
2017/03/26 14:21:03.358991 VERBOSE run cmd 'sync'
2017/03/26 14:21:03.415748 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/26 14:21:03.440595 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
2017/03/26 14:21:03.440718 VERBOSE run cmd 'sfdisk -R /dev/sdb'
```
It seems hit the "output.find("is already mounted") != -1" condition so I think it works well. I'll keep trying more times to confirm that. Thanks!

**Comment by vittyvk** [comment]
Thanks! I would suppose it also works without 'sync' added. Can you please try?
The WARNING above is expected.

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,

I remove the "sync" line:
```
167         logger.info("Mount resource disk [{0}]", mount_string)
168 #        ret, output = shellutil.run_get_output("sync")
169         ret, output = shellutil.run_get_output(mount_string, chk_err=False)
170         # if the exit code is 32, then the resource disk is already mounted
171 #        if ret == 32:
172         if ret == 32 and output.find("is already mounted") != -1:
173             logger.warn("Could not mount resource disk: {0}", output)
174         elif ret != 0:
175             # Some kernels seem to issue an async partition re-read after a
176             # 'parted' command invocation. This causes mount to fail if the
177             # partition re-read is not complete by the time mount is
178             # attempted. Seen in CentOS 7.2. Force a sequential re-read of
179             # the partition and try mounting.
180             logger.warn("Failed to mount resource disk. "
181                         "Retry mounting after re-reading partition info.")
182 
183             if shellutil.run("sfdisk -R {0}".format(device), chk_err=False):
184                 shellutil.run("blockdev --rereadpt {0}".format(device),
185                               chk_err=False)
186 
187             ret, output = shellutil.run_get_output(mount_string)
188             if ret:
189                 logger.warn("Failed to mount resource disk. "
190                             "Attempting to format and retry mount. [{0}]",
191                             output)
192 
193                 shellutil.run(mkfs_string)
194                 ret, output = shellutil.run_get_output(mount_string)
195                 if ret:
196                     raise ResourceDiskError("Could not mount {0} "
197                                             "after syncing partition table: "
198                                             "[{1}] {2}".format(partition,
199                                                                ret,
200                                                                output))
201 
202         logger.info("Resource disk {0} is mounted at {1} with {2}",
```

I tried 444 times and it works well. But there're some error logs:
```
2017/03/27 22:20:00.979199 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/03/27 22:20:00.979282 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/27 22:20:01.009212 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
2017/03/27 22:20:01.009407 VERBOSE run cmd 'sfdisk -R /dev/sdb'
2017/03/27 22:20:01.089372 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/27 22:20:01.137672 ERROR run cmd 'mount /dev/sdb1 /mnt/resource' failed
2017/03/27 22:20:01.137868 ERROR Error Code:32
2017/03/27 22:20:01.137949 ERROR Result:mount: special device /dev/sdb1 does not exist

2017/03/27 22:20:01.138073 WARNING Failed to mount resource disk. Attempting to format and retry mount. [mount: special device /dev/sdb1 does not exist
]
2017/03/27 22:20:01.138159 VERBOSE run cmd 'mkfs.ext4 /dev/sdb1 -F'
2017/03/27 22:20:03.908012 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/03/27 22:20:04.330256 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
```

It seems that the mount command in line#187 is still failed, and then then line#194 command succeeds. (It's a rare thing that happened 2/444 times). I'm not quite sure that if there's a possibility that the line#194 command is still failed, although it isn't observed till now. Is there a risk?

Base on the test result, it seems that the "if ret == 32 and output.find("is already mounted") != -1:" without the "sync" command works well. I'll try more times to confirm that. Thanks!

**Comment by vittyvk** [comment]
I submitted https://github.com/Azure/WALinuxAgent/pull/629 yesterday with this and a couple of relevant fixes to make resource disk mount more stable. Thanks for your testing!

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,

Thanks. I'll try your code in #629 today.

About the last test (only add "if ret == 32 and output.find("is already mounted") != -1:" line), there's a strange error at the 631th reboot:
```
2017/03/28 08:19:02.968697 INFO Activate resource disk
2017/03/28 08:19:02.980558 VERBOSE run cmd 'mount'
2017/03/28 08:19:03.095378 INFO Examining partition table
2017/03/28 08:19:03.095547 VERBOSE run cmd 'parted /dev/sdb print'
2017/03/28 08:19:03.164965 INFO GPT not detected, determining filesystem
2017/03/28 08:19:03.182380 VERBOSE run cmd 'sfdisk --part-type -f /dev/sdb 1'
2017/03/28 08:19:03.252121 INFO sfdisk with --part-type failed [1], retrying with -c
2017/03/28 08:19:03.252276 VERBOSE run cmd 'sfdisk -c -f /dev/sdb 1'
2017/03/28 08:19:03.262909 INFO sfdisk -c -f /dev/sdb 1 succeeded
2017/03/28 08:19:03.263029 INFO The partition type is 83
2017/03/28 08:19:03.292604 ERROR Failed to mount resource disk (000005)Partition was not created [/dev/sdb1]
2017/03/28 08:19:03.292965 ERROR Event: name=WALA, op=ActivateResourceDisk, message=(000005)Partition was not created [/dev/sdb1]
2017/03/28 08:19:03.294235 INFO Clean protocol
2017/03/28 08:19:03.301682 INFO Provisioning already completed, skipping.
```

It appears to doesn't hit the file check in line#157 but hit the line#164:
```
156         attempts = 5
157         while not os.path.exists(partition) and attempts > 0:
158             logger.info("Waiting for partition [{0}], {1} attempts remaining",
159                         partition,
160                         attempts)
161             sleep(5)
162             attempts -= 1
163 
164         if not os.path.exists(partition):
165             raise ResourceDiskError("Partition was not created [{0}]".format(partition))
```
I have to say it is out of my understanding...perhaps the /dev/sdb1 existed temporarily and then disappeared?

**Comment by vittyvk** [comment]
Second patch from https://github.com/Azure/WALinuxAgent/pull/629 should help: 'sfdisk -c -f /dev/sdb 1" leads to partition table re-read in RHEL7 (but not upstream), to avoid it '-n' should be added.

**Comment by yuxisun1217** [comment]
Got it @vittyvk . Thanks!

**Comment by yuxisun1217** [comment]
Hi @vittyvk ,
I tried 700+ times with your commit #629 and it worked well.

**Comment by hglkrijger** [comment]
The fix is merged, closing.
